# 1. Tên của Workflow (hiển thị trên tab Actions)
name: Hello @hoidanit

# 2. Trigger: Khi nào thì chạy?
on:
  push:
    branches: ["dev"] # Chạy khi push/merge code vào branch main
  workflow_dispatch: # Tạo nút bấm "Run workflow" để chạy bằng tay

# 3. Danh sách các công việc (Jobs)
jobs:
  say-hello-job:
    # Chạy trên máy ảo Ubuntu
    runs-on: ubuntu-latest

    # 4. Các bước thực hiện (Steps)
    steps:
      # Bước 1: Lấy code từ repo về máy ảo (Dùng Action có sẵn)
      - name: Step 1 Checkout repository
        uses: actions/checkout@v6

      # Bước 2: Chạy lệnh shell (Dùng lệnh echo của Linux)
      - name: Step 2 Print greeting message
        run: |
          echo "Xin chao @hoidanit!"
          echo "Chuc mung ban da khoi tao Workflow thanh cong."
          echo "Hien tai dang chay tren: $(lsb_release -d)"

      # Bước 3: Kiểm tra
      - name: Step 3 Check if Node.js is installed
        run: pwd && ls -a && node -v

      - name: Dung Secret cua Repo
        run: echo "SECRET NAME = ${{ secrets.MY_SECRET_NAME }}"
      - name: Dung Variable cua Repo
        run: echo "VAR NAME = ${{ vars.MY_VARIABLE_NAME }}"
